name = "trmnl-cf-ip"
main = "worker.js"
compatibility_date = "2026-01-30"

[[kv_namespaces]]
binding = "IP_STORE"
id = "e402ff03be724d09bd52f0ab61acc295"

[[routes]]
pattern = "ip.t.r1l.in"
custom_domain = true